blogTitle: "My React Markdown Blog"
homepageHeroImageUrl: "/images/post-image.jpg" # A placeholder hero image for the homepage
gaMeasurementId: "G-XXXXXXXXXX" # Replace with your actual Google Analytics Measurement ID
