blogTitle: "My React Markdown Blog"
homepageHeroImageUrl: "https://picsum.photos/seed/homepage-hero/1200/400" # A placeholder hero image for the homepage
gaMeasurementId: "G-XXXXXXXXXX" # Replace with your actual Google Analytics Measurement ID
