import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import CookieConsentBanner from "../components/CookieConsentBanner";
import AnalyticsRouteChangeTracker from "../components/AnalyticsRouteChangeTracker";
import GoogleAnalyticsLoader from "../components/GoogleAnalyticsLoader";
import Footer from "../components/Footer";
import PrelineInit from "../components/PrelineInit";
import ThemeScript from "../components/ThemeScript";
import { SiteConfigProvider } from "../contexts/SiteConfigContext";
import { CookieConsentProvider } from "../contexts/CookieConsentContext";
import { ThemeProvider } from "../contexts/ThemeContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeScript />
      </head>
      <body className="antialiased">
        <ThemeProvider>
          <SiteConfigProvider>
            <CookieConsentProvider>
              <div className="flex flex-col min-h-screen">
                <Navbar />
                <main className="flex-grow py-8">
                  <AnalyticsRouteChangeTracker />
                  <GoogleAnalyticsLoader />
                  <PrelineInit />
                  {children}
                </main>
                <CookieConsentBanner />
                <Footer />
              </div>
            </CookieConsentProvider>
          </SiteConfigProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
