import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import CookieConsentBanner from "../components/CookieConsentBanner";
import AnalyticsRouteChangeTracker from "../components/AnalyticsRouteChangeTracker";
import GoogleAnalyticsLoader from "../components/GoogleAnalyticsLoader";
import Footer from "../components/Footer";
import { SiteConfigProvider } from "../contexts/SiteConfigContext";
import { CookieConsentProvider } from "../contexts/CookieConsentContext";
import { ThemeProvider } from "../contexts/ThemeContext";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={`${inter.className} antialiased bg-white text-gray-900 dark:bg-black dark:text-gray-100`}>
        <ThemeProvider>
          <SiteConfigProvider>
            <CookieConsentProvider>
              <div className="flex flex-col min-h-screen">
                <Navbar />
                <main className="flex-grow bg-gray-50 dark:bg-gray-900 py-8">
                  <AnalyticsRouteChangeTracker />
                  <GoogleAnalyticsLoader />
                  {children}
                </main>
                <CookieConsentBanner />
                <Footer />
              </div>
            </CookieConsentProvider>
          </SiteConfigProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
