import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import CookieConsentBanner from "../components/CookieConsentBanner";
import AnalyticsRouteChangeTracker from "../components/AnalyticsRouteChangeTracker";
import GoogleAnalyticsLoader from "../components/GoogleAnalyticsLoader";
import Footer from "../components/Footer";
import { SiteConfigProvider } from "../contexts/SiteConfigContext";
import { CookieConsentProvider } from "../contexts/CookieConsentContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SiteConfigProvider>
          <CookieConsentProvider>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-grow bg-gray-100 py-8">
                <AnalyticsRouteChangeTracker />
                <GoogleAnalyticsLoader />
                {children}
              </main>
              <CookieConsentBanner />
              <Footer />
            </div>
          </CookieConsentProvider>
        </SiteConfigProvider>
      </body>
    </html>
  );
}
